### ISSUE TITLE
Does it also send back response?

### ISSUE THREAD

**Issue by amrit92** [Snawoot/steady-tun#6]
Does it relay back response after forwarding to TCP  dest?

**Comment by Snawoot** [comment]
Yeah, it does. Those are bidirectional connections. What's your case? Give me an example.

**Comment by amrit92** [comment]
I'm trying the following:

App (JDBC etc) -> Socks5 proxy / TCP -> Steady-tun (send proxyprotocol header then do TLS) -> Secure endpoint

I need to explore how to add Socks5 and the proxyprotocol header.

**Comment by Snawoot** [comment]
Ah, right! Yeah, should work. But I can't get what do you need SOCKS5 for in your scheme? Is this the only way for an app to reach network location where steady-tun can be hosted? If you'd like to just wrap your conn into TLS, steady-tun is sufficient (except PP thing, this one needs a bit of customization).

**Comment by amrit92** [comment]
Yes, its for apps which are just limited to SOCKS proxy and I can't edit their source. They would tunnel through SOCKS and then customized steady-tun would add header + encrypt/decrypt traffic to secure endpoint.

**Comment by flikites** [comment]
> Yes, its for apps which are just limited to SOCKS proxy and I can't edit their source. They would tunnel through SOCKS and then customized steady-tun would add header + encrypt/decrypt traffic to secure endpoint.

We're you ever able to get a proper setup with the SOCKS configuration? @amrit92
